os:
    - linux
language: node_js
install: true
node_js:
    - '10'
script:
    - echo '0. Global install'
    - npm ci
    - echo '1. todomvc global install'
    - cd todomvc
    - npm ci
    - bash install-all.sh
    - echo '2. todomvc build all implementations'
    - npm run build:all
    - cd ../
    - echo '3. pascal-triangle global install'
    - cd pascal-triangle
    - npm ci
    - bash install-all.sh
    - echo '4. pascal-triangle build all implementations'
    - npm run build:all
    - cd ../
    - echo '5. copy demos'
    - npm run copy-demos
    - npm run serve
    - cd pascal-triangle
    - echo '6. pascal-triangle / run benchmark'
    - npm run run:benchmark
    - cd ../todomvc
    - echo '7. todomvc / run benchmark'
    - npm run run:benchmark
    - cd ../
    - echo '8. compile results'
    - npm run compile-results
    - bash scripts/deploy.sh
branches:
    only:
        - master
env:
    global:
        - secure: YoCqtnHUCytOtxaAdgpef1b3Q2paWm72wrH5tWU+9WncW2W9rpe7xZ8zkytINc7gRHtHC2xL6aWKDxyFOqrqLTD8y0An65mR5ENXTdG8sx/emibDhV8y6rwdGhoWac1WolkAuCIWkTfW4xJsgLaHiM2DpVGswttsixa67IIWt3dQFzt+EQ6wZ2rxPASUD5MVYI21A4b7XsLhjZ1a+tMxOFE92IqjLdwYt1NNTPMT7PSibpQ9dr0Mi9p/v3LLkgKXE54QRqL0yeUzZxa5MOd5gJ2QPCnfiGL2hTuV68kz+ekl00X3NuxhPTlJ4Suer94LFT92B4tSqOKt6FlbUa5mQMgfBzmUl949zZP9q1AuV6hLG/+f2xxxinLSFSvgK8n0RUSs4g9iY2mSB0go1iKBj0GlhEI0WDQXfZPCNQLf5Kv0B2kjDxRVK48qk8/SD3QpNPh+gb2AahKrnyh7yk4EDln7c9+5lZRu6EnC5Xp0XCaA3VQsS6rLoWBUYIjcQaELDxbiGbhjcSM1+tc3CzAXvKpKXCAFEXqVkVdH8Jj2D31/uNTqX/3Kjs3+r45+7vslDCGY4vA9M075TzLj7A4uTs/NDkaBZo0x/QcvUyqS19ZcbKa8sxyuEw1kVGDgGBa0qF5X7U2K5X6VMEoh7QxHkcTPDyZy5IeBl7aJHgWqLDw=
